language: cpp

addons:
  apt:
    packages:
    - libc6-dbg
    - libc6-dev
    - libc6:i386
    - libc6-dev-i386
    - libc6-dbg:i386
    - gcc-multilib
    - lua5.1
    - liblua5.1-0
    - luajit 
    - libluajit-5.1
    - libgtest-dev
    - valgrind

env:
  global:
    - LANG="zh_CN.UTF-8"
  matrix:
    - TRAVIS_OS_NAME=osx CC=clang CXX=clang
    - TRAVIS_OS_NAME=osx CC=gcc CXX=gcc
    - TRAVIS_OS_NAME=linux CC=gcc CXX=gcc
    - TRAVIS_OS_NAME=linux CC=clang CXX=clang

after_success:
  - bin/owent_utils_test
  
script: 
  - REPO_DIR=$PWD
  - mkdir -p tools && cd tools
  - CMAKE_PREFIX=$PWD/prebuilt/cmake
  - if [ ! -e "$CMAKE_PREFIX/bin/cmake" ]; then
        wget -c "https://github.com/Kitware/CMake/archive/v3.4.1.tar.gz" -O CMake-3.4.1.tar.gz ;
        tar -axvf CMake-3.4.1.tar.gz > build_cmake.log 2>&1 ;
        cd CMake-3.4.1 ;
        ./bootstrap --prefix=$CMAKE_PREFIX  >> build_cmake.log 2>&1 ;
        make -j4 install  >> build_cmake.log 2>&1 ;
    fi
  - mkdir -p $REPO_DIR/build && cd $REPO_DIR/build ;
  - $CMAKE_PREFIX/bin/cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX;
  - make -j4 ;

install: true

cache: 
    apt: true
    directories:
    - $CMAKE_PREFIX
    
branches:
  only:
    - master

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
