language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install -qq lua5.1 liblua5.1-* libgtest-dev
  
after_success:
  - bin/owent_utils_test
  
script: 
  - REPO_DIR=$PWD
  - mkdir -p tools && cd tools
  - CMAKE_PREFIX=$PWD/prebuilt/cmake
  - if [ ! -e "$CMAKE_PREFIX/bin/cmake" ]; then
        wget -c "https://github.com/Kitware/CMake/archive/v3.4.1.tar.gz" -O CMake-3.4.1.tar.gz ;
        tar -axvf CMake-3.4.1.tar.gz > build_cmake.log 2>&1 ;
        cd CMake-3.4.1 ;
        ./bootstrap --prefix=$CMAKE_PREFIX  >> build_cmake.log 2>&1 ;
        make -j4 install  >> build_cmake.log 2>&1 ;
    fi
  - mkdir -p $REPO_DIR/build && cd $REPO_DIR/build ;
  - $CMAKE_PREFIX/bin/cmake .. ;
  - make -j4 ;

install: true

cache: 
    apt: true
    directories:
    - $CMAKE_PREFIX
    
branches:
  only:
    - master

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"

env:
  - LANG="zh_CN.UTF-8"

os:
  - linux
  - osx
