language: cpp

compiler:
  - gcc
  - cmake

before_script:
  - sudo apt-get install -qq cmake lua5.1 liblua5.1-*
  - mkdir -p build && cd build && cmake ..

after_success:
  - bin/owent_utils_test
  
script: 
  - make -j4

install: true

branches:
  only:
    - master

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"

env:
  - LANG="zh_CN.UTF-8"

os:
  - linux
  - osx

osx_image: xcode61
